### ISSUE TITLE
Instructions incorrect

### ISSUE THREAD

**Issue by DFINITYManu** [NikolaMilosa/ntfs-undelete#15]
```
Creating symbolic links for static libs
sudo ln -s /usr/local/lib/libtsk.a /usr/local/lib/liblibtsk.a
sudo ln -s usr/local/lib/libtsk.so /usr/local/lib/liblibtsk.so
```

Typo on the first path of the second command.  Also, aren't the libraries that the symlinks point to, stored in /usr/lib instead?

**Comment by nikola-milosa** [comment]
Depends how you install them. If you installed them following the basic instruction from [here](https://github.com/sleuthkit/sleuthkit/blob/develop/INSTALL.txt) they will be in /usr/local/. 
Thanks for the point out in typo!
